#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
         fakeroot kmod cpio git python3-docutils gettext automake autopoint \
         texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
         libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        git clone https://github.com/silveryxx/Padavan.git /opt/rt-n56u
    - name: Run shellcheck
      run: |
        cd /opt/rt-n56u
        sh ./trunk/tools/shellcheck.sh
    - name: Prepare toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
    - name: Build Firmware
      env:
        TNAME: "K2P"
        images_dir: /opt/images
      run: |
        mkdir -p ${images_dir}
        cd /opt/rt-n56u/trunk/user/shared
        sed -i 's/192.168.2/192.168.1/g' defaults.h
        sed -i 's/ASUS/Silvery/g' defaults.h
        sed -i 's/1234567890/mkd1230.+/g' defaults.h
        sed -i 's/147852369/Feng*963./g' defaults.h
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
    - name: Upload images to Releases
      if: always()
      uses: svenstaro/upload-release-action@2.2.0
      with:
        repo_token: ${{ secrets.workflow_token }}
        file: /opt/images/*.trx
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
